services:
  cf-edge-watcher:
    image: creator1021/cf-edge-watcher:test
    container_name: cf-edge-watcher-test
    restart: unless-stopped
    env_file:
     - ./local/.env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"